[package]
name = "eos"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.0.7", features = ["derive"] }
colored = "2.0.0"
rayon = "1.5.3"
serde = "1.0.145"
serde_derive = "1.0.145"
toml = "0.5.9"
