= Eos

Eos is a build tool for illumos. It works by locating `build.toml` files in the
illumos source tree and generating a top-level ninja build specification based
on the contents of those files. The user can then simply run `ninja` to build
illumos.

== Why

- The current illumos build system is hostile to git workflows. Running `git
  status -uall` currently shows over 50,000 files after a nightly build when no
  actual source files have been changed. This can lead to lost work by losing
  track of the needle that is your code in this massive haystack - ask me how I
  know. Eos puts **_everything generated by the build process_** in a top level
  `bld` directory.

- On a top-of-the-line workstation today, illumos takes about 30 minutes to
  build completely using the nightly scripts (about 15 minutes in quick mode).
  The goal here is to do better by an order of magnitude by taking a fresh look
  at the build system, not within the context of the current build system, but
  by asking: how do we produce the needed artifacts in the simplest and fastest
  way possible.

- Trade a complex imperative makefile system for a simple collection of
  declarative build specifications.

== How

illumos is a vast body of software, so this is a rather large undertaking. It
cannot happen all at once, and it will require the expertise of many people. The
goal here is to incrementally grow Eos and the associated illumos 
https://github.com/oxidecomputer/illumos-gate/tree/eos[branch]
containing Eos build specifications until we are capable of building everything.
The status section below keeps track of where we are at.

== Contributing

There are several ways to contribute to Eos

1. Add new build specs to advance illumos coverage.
2. More advanced ninja usage.
3. Add new build types (e.g. user libraries, commands, etc).
4. Add additional tooling, can we replace dmake _and_ nightly with a one-stop
shop tool?

== Status

=== Kernel
* https://github.com/oxidecomputer/illumos-gate/blob/eos/usr/src/uts/common/build.toml[genunix]
* https://github.com/oxidecomputer/illumos-gate/blob/eos/usr/src/uts/common/inet/ip/build.toml[ip]

=== Libraries

=== Commands

== Usage

----
git clone -b eos https://github.com/oxidecomputer/illumos-gate
cd illumos-gate
eos
ninja
----

At this point you will have a build tree in the `bld` directory. You can take a
look at the generated ninja file `build.ninja`.
